apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: wil-playground
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
        resources:
          limits:
            ephemeral-storage: "500Mi"
          requests:
            ephemeral-storage: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
